# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainFormUI(object):
    def setupUi(self, MainFormUI):
        MainFormUI.setObjectName("MainFormUI")
        MainFormUI.resize(605, 347)
        MainFormUI.setMinimumSize(QtCore.QSize(605, 347))
        MainFormUI.setMaximumSize(QtCore.QSize(605, 347))
        self.centralwidget = QtWidgets.QWidget(MainFormUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(10, 15, 10, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(1010, 100101))
        self.tabWidget.setObjectName("tabWidget")
        self.tabLocal = QtWidgets.QWidget()
        self.tabLocal.setObjectName("tabLocal")
        self.gridLayout = QtWidgets.QGridLayout(self.tabLocal)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tabLocal)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditLocalName = QtWidgets.QLineEdit(self.tabLocal)
        font = QtGui.QFont()
        font.setBold(True)
        self.lineEditLocalName.setFont(font)
        self.lineEditLocalName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditLocalName.setReadOnly(True)
        self.lineEditLocalName.setObjectName("lineEditLocalName")
        self.horizontalLayout.addWidget(self.lineEditLocalName)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tabLocal)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditClientID = QtWidgets.QLineEdit(self.tabLocal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditClientID.setFont(font)
        self.lineEditClientID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditClientID.setReadOnly(True)
        self.lineEditClientID.setObjectName("lineEditClientID")
        self.horizontalLayout_2.addWidget(self.lineEditClientID)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tabLocal)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.textEditLocalDescription = QtWidgets.QTextEdit(self.tabLocal)
        self.textEditLocalDescription.setReadOnly(True)
        self.textEditLocalDescription.setObjectName("textEditLocalDescription")
        self.gridLayout.addWidget(self.textEditLocalDescription, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabLocal, "")
        self.tabRemoteClients = QtWidgets.QWidget()
        self.tabRemoteClients.setObjectName("tabRemoteClients")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabRemoteClients)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetRemoteClients = QtWidgets.QListWidget(self.tabRemoteClients)
        self.listWidgetRemoteClients.setObjectName("listWidgetRemoteClients")
        self.verticalLayout_2.addWidget(self.listWidgetRemoteClients)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonUpdateRemoteList = QtWidgets.QPushButton(self.tabRemoteClients)
        self.pushButtonUpdateRemoteList.setObjectName("pushButtonUpdateRemoteList")
        self.horizontalLayout_4.addWidget(self.pushButtonUpdateRemoteList)
        self.pushButtonControlConnection = QtWidgets.QPushButton(self.tabRemoteClients)
        self.pushButtonControlConnection.setObjectName("pushButtonControlConnection")
        self.horizontalLayout_4.addWidget(self.pushButtonControlConnection)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tabRemoteClients, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEditServerName = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditServerName.setFont(font)
        self.lineEditServerName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditServerName.setReadOnly(True)
        self.lineEditServerName.setObjectName("lineEditServerName")
        self.horizontalLayout_6.addWidget(self.lineEditServerName)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEditConnectionStatus = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditConnectionStatus.setFont(font)
        self.lineEditConnectionStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditConnectionStatus.setReadOnly(True)
        self.lineEditConnectionStatus.setObjectName("lineEditConnectionStatus")
        self.horizontalLayout_7.addWidget(self.lineEditConnectionStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEditHostName = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditHostName.setFont(font)
        self.lineEditHostName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditHostName.setReadOnly(True)
        self.lineEditHostName.setObjectName("lineEditHostName")
        self.horizontalLayout_8.addWidget(self.lineEditHostName)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonStartService = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonStartService.setObjectName("pushButtonStartService")
        self.verticalLayout_3.addWidget(self.pushButtonStartService)
        self.pushButtonStopService = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonStopService.setObjectName("pushButtonStopService")
        self.verticalLayout_3.addWidget(self.pushButtonStopService)
        self.pushButtonQuit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.verticalLayout_3.addWidget(self.pushButtonQuit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 1, 1, 1)
        MainFormUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainFormUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 22))
        self.menubar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainFormUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainFormUI)
        self.statusbar.setObjectName("statusbar")
        MainFormUI.setStatusBar(self.statusbar)
        self.actionEditServer = QtWidgets.QAction(MainFormUI)
        self.actionEditServer.setObjectName("actionEditServer")
        self.actionChangeServer = QtWidgets.QAction(MainFormUI)
        self.actionChangeServer.setObjectName("actionChangeServer")
        self.actionEditLocalClient = QtWidgets.QAction(MainFormUI)
        self.actionEditLocalClient.setObjectName("actionEditLocalClient")
        self.actionSaveLocalClient = QtWidgets.QAction(MainFormUI)
        self.actionSaveLocalClient.setObjectName("actionSaveLocalClient")
        self.actionAboutQt5 = QtWidgets.QAction(MainFormUI)
        self.actionAboutQt5.setObjectName("actionAboutQt5")
        self.actionAboutProgram = QtWidgets.QAction(MainFormUI)
        self.actionAboutProgram.setObjectName("actionAboutProgram")
        self.menuFile.addAction(self.actionEditServer)
        self.menuFile.addAction(self.actionChangeServer)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEditLocalClient)
        self.menuFile.addAction(self.actionSaveLocalClient)
        self.menuHelp.addAction(self.actionAboutQt5)
        self.menuHelp.addAction(self.actionAboutProgram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainFormUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainFormUI)
        MainFormUI.setTabOrder(self.tabWidget, self.lineEditLocalName)
        MainFormUI.setTabOrder(self.lineEditLocalName, self.lineEditClientID)
        MainFormUI.setTabOrder(self.lineEditClientID, self.textEditLocalDescription)
        MainFormUI.setTabOrder(self.textEditLocalDescription, self.lineEditServerName)
        MainFormUI.setTabOrder(self.lineEditServerName, self.lineEditConnectionStatus)
        MainFormUI.setTabOrder(self.lineEditConnectionStatus, self.lineEditHostName)
        MainFormUI.setTabOrder(self.lineEditHostName, self.pushButtonStartService)
        MainFormUI.setTabOrder(self.pushButtonStartService, self.pushButtonStopService)
        MainFormUI.setTabOrder(self.pushButtonStopService, self.pushButtonQuit)
        MainFormUI.setTabOrder(self.pushButtonQuit, self.listWidgetRemoteClients)
        MainFormUI.setTabOrder(self.listWidgetRemoteClients, self.pushButtonUpdateRemoteList)
        MainFormUI.setTabOrder(self.pushButtonUpdateRemoteList, self.pushButtonControlConnection)

    def retranslateUi(self, MainFormUI):
        _translate = QtCore.QCoreApplication.translate
        MainFormUI.setWindowTitle(_translate("MainFormUI", "微软远程桌面——内网穿透助手 Mac版"))
        self.label.setText(_translate("MainFormUI", "名称"))
        self.label_2.setText(_translate("MainFormUI", "编号"))
        self.label_3.setText(_translate("MainFormUI", "描述"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLocal), _translate("MainFormUI", "本机信息"))
        self.pushButtonUpdateRemoteList.setText(_translate("MainFormUI", "更新"))
        self.pushButtonControlConnection.setText(_translate("MainFormUI", "连接"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRemoteClients), _translate("MainFormUI", "远程客户端"))
        self.groupBox.setTitle(_translate("MainFormUI", "代理服务器信息"))
        self.label_4.setText(_translate("MainFormUI", "名称"))
        self.label_5.setText(_translate("MainFormUI", "状态"))
        self.label_6.setText(_translate("MainFormUI", "地址"))
        self.groupBox_2.setTitle(_translate("MainFormUI", "程序控制"))
        self.pushButtonStartService.setText(_translate("MainFormUI", "启动服务"))
        self.pushButtonStopService.setText(_translate("MainFormUI", "停止服务"))
        self.pushButtonQuit.setText(_translate("MainFormUI", "退出应用"))
        self.menuFile.setTitle(_translate("MainFormUI", "编辑"))
        self.menuHelp.setTitle(_translate("MainFormUI", "帮助"))
        self.actionEditServer.setText(_translate("MainFormUI", "编辑代理服务器"))
        self.actionEditServer.setShortcut(_translate("MainFormUI", "Ctrl+Shift+E"))
        self.actionChangeServer.setText(_translate("MainFormUI", "更换代理服务器"))
        self.actionChangeServer.setShortcut(_translate("MainFormUI", "Ctrl+Shift+C"))
        self.actionEditLocalClient.setText(_translate("MainFormUI", "编辑本机信息"))
        self.actionEditLocalClient.setShortcut(_translate("MainFormUI", "Ctrl+Shift+L"))
        self.actionSaveLocalClient.setText(_translate("MainFormUI", "保存本机信息"))
        self.actionSaveLocalClient.setShortcut(_translate("MainFormUI", "Ctrl+Shift+S"))
        self.actionAboutQt5.setText(_translate("MainFormUI", "关于Qt 5"))
        self.actionAboutQt5.setShortcut(_translate("MainFormUI", "Shift+Q"))
        self.actionAboutProgram.setText(_translate("MainFormUI", "关于应用"))
        self.actionAboutProgram.setShortcut(_translate("MainFormUI", "Ctrl+Shift+A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormUI = QtWidgets.QMainWindow()
    ui = Ui_MainFormUI()
    ui.setupUi(MainFormUI)
    MainFormUI.show()
    sys.exit(app.exec_())

